### ISSUE TITLE
Allow modification of account and registration key

### ISSUE THREAD

**Issue by WebSpider** [mrlesmithjr/ansible-landscape-client#1]
**Is your feature request related to a problem? Please describe.**
The current version of the playbook doesnt allow configuring the landscape account (landscape-config --account-name) and the registration key (landscape-config --registration-key, resulting in not being able to register the computer to specific landscape accounts

**Describe the solution you'd like**
Support for --account-name and --registration-key in register.yml

**Describe alternatives you've considered**
Rerunning configuration in an alternate play, but it's not as smooth

**Comment by mrlesmithjr** [comment]
Thank you for this feature request to support `--account-name` and `--registration-key` options.

Closing this issue due to age (3+ years without activity). If this feature is still needed, please feel free to:

1. Open a new issue with current requirements
2. Submit a PR - the change would be straightforward:
   - Add variables like `landscape_account_name` and `landscape_registration_key` to defaults
   - Update the `register.yml` task to include these options when defined

Example implementation:
```yaml
# In defaults/main.yml
landscape_account_name: ""
landscape_registration_key: ""

# In register.yml command
landscape-config \
  {% if landscape_account_name %}--account-name {{ landscape_account_name }}{% endif %} \
  {% if landscape_registration_key %}--registration-key {{ landscape_registration_key }}{% endif %}
```

PRs welcome!
